### PR TITLE
First attempt for roles in mesosphere.

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Comment by johngian** [comment]
Please update `README.md` with something specific to each role.

**Comment by johngian** [comment]
I am not sure why we need `app/marathon-test-docker.json`. Can we somehow use it with ansible?

**Comment by akatsoulas** [comment]
We could add a task to "deploy" the container to marathon.

**Comment by johngian** [comment]
Ok let's leave it this way.

**Pull request merged**
